/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    signing
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compileOnly("com.fasterxml.jackson.module", "jackson-module-kotlin")
    // Align versions of all Kotlin components
    implementation(platform(kotlin("bom", "1.8.20")))
    compileOnly(platform("org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.6.4"))
    // Use the Kotlin JDK 8 standard library.
    compileOnly(kotlin("stdlib"))
    // Use the Kotlin test library.
    testImplementation(kotlin("test"))
    // Use the Kotlin JUnit integration.
    testImplementation(kotlin("test-junit5"))

    compileOnly("org.jetbrains.kotlinx", "kotlinx-coroutines-reactor")
    // Align versions of all SpringBoot components
    implementation(platform("org.springframework.boot:spring-boot-dependencies:3.0.5"))
}

tasks.test {
    useJUnitPlatform()
}
