/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

group = "cn.repigeons"
version = "1.1.0-RELEASE"

plugins {
    kotlin("jvm") version "1.8.20"
    `build-conventions`
}

dependencies {
    compileOnly(project(":spring-boot-commons-core"))
    compileOnly(project(":spring-boot-cache"))
    compileOnlyApi("$group", "spring-boot-commons-core", "$version")
    compileOnlyApi("$group", "spring-boot-cache", "$version")

    compileOnly("org.slf4j", "slf4j-api")
    compileOnly("org.apache.tomcat.embed", "tomcat-embed-core")

    compileOnly("org.springframework", "spring-web")
    compileOnly("org.springframework", "spring-context")
    compileOnly("org.springframework.boot", "spring-boot-autoconfigure")
}

publishing {
    val sourceJar = tasks.register("sourcesJar", Jar::class) {
        sourceSets.all { from(allSource) }
        archiveClassifier.convention("sources")
        archiveClassifier.set("sources")
    }
    val javadocJar = tasks.register("javadocJar", Jar::class) {
        archiveClassifier.convention("javadoc")
        archiveClassifier.set(name)
    }
    publications {
        create<MavenPublication>("maven") {
            from(components["kotlin"])
            artifact(sourceJar)
            artifact(javadocJar)
        }
    }
    repositories {
        maven {
            if (version.toString().endsWith("-RELEASE")) {
                setUrl("https://mirrors.repigeons.cn/repository/maven-releases/")
            } else if (version.toString().endsWith("-SNAPSHOT")) {
                setUrl("https://mirrors.repigeons.cn/repository/maven-snapshots/")
            }
            credentials {
                username = System.getenv("REPIGEONS_REPOSITORY_USERNAME")
                password = System.getenv("REPIGEONS_REPOSITORY_PASSWORD")
                println("username=$username")
                println("password=$password")
            }
        }
    }
}
